services:
  api:
    build: ./api
    container_name: api
    ports:
      - "8000:80"
    volumes:
      - ./api/:/code/
    command: sh ./run.sh
    networks:
      - shopping

  next-frontend:
    build: ./nextui
    container_name: next-frontend
    ports:
      - "80:3000"
    depends_on:
      - api
    networks:
      - shopping

networks:
  shopping:
    driver: bridge
