services:
  api:
    build: ./api
    container_name: api
    ports:
      - "8000:80"
    volumes:
      - ./api/:/code/
    command: sh ./run.sh
    networks:
      - shopping

  frontend:
    build: ./UI
    container_name: frontend
    ports:
      - "80:80"
    volumes:
      - ./UI/dist:/usr/share/nginx/html:ro
      - ./UI/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - api
    networks:
      - shopping

networks:
  shopping:
    driver: bridge